version: '3.8'

services:
  sage-bg:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      # - DATABASE_URL=your_database_url
      # - OPENROUTER_API_KEY=your_openrouter_api_key
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sage-network

  # Optional: Add PostgreSQL for local development
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: sage_bg
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - sage-network

networks:
  sage-network:
    driver: bridge

# volumes:
#   postgres_data: 